general {
    no_fade_in = false
    no_fade_out = true
    hide_cursor = true
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /usr/share/sddm/themes/corners/backgrounds/login_bg_blur.png
    color = rgba(0, 0, 0, 1.0)
}

animations {
    enabled = true
    bezier = linear, 1, 1, 1, 1
    animation = fadeIn, 1, 30, linear # Fundido de 30 frames para tapar todo
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    dots_center = true
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(224, 179, 255)
    position = 0, -140
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(255, 255, 255)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 100
    halign = center
    valign = center
}
